import { AuthProvider } from '@/providers/AuthProvider';
import './globals.css';
import { Inter } from 'next/font/google';
import { LoaderProvider } from '@/providers/LoaderContextProvider';
import { ReducerProvider } from '@/providers/useReducerProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<AuthProvider>
				<LoaderProvider>
					<ReducerProvider>
						<body className={inter.className}>{children}</body>
					</ReducerProvider>
				</LoaderProvider>
			</AuthProvider>
		</html>
	);
}
